name: flutter_bluetooth_printer
description: Image based printing for bluetooth thermal printer, support for iOS and Android.
version: 2.20.0
repository: https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin

false_secrets:
  - example/**

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter_bluetooth_printer_platform_interface: ^0.0.7
  flutter_bluetooth_printer_web: ^1.1.1
  flutter_bluetooth_printer_macos: ^1.3.0
  plugin_platform_interface: ^2.1.3
  flutter:
    sdk: flutter

  image: ">=4.1.7"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: id.flutter.plugins
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: MethodChannelBluetoothPrinter
      ios:
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: MethodChannelBluetoothPrinter
      web:
        default_package: flutter_bluetooth_printer_web

  fonts:
    - family: Receipt
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 600
