name: flutter_bluetooth_printer
description: Image based printing for bluetooth thermal printer, support for iOS and Android.
version: 2.16.10
repository: https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image: ">=4.1.7"
  flutter_bluetooth_printer_platform_interface: ^0.0.7
  plugin_platform_interface: ^2.1.2
  flutter_bluetooth_printer_macos: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: id.flutter.plugins
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: MethodChannelBluetoothPrinter
      ios:
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: MethodChannelBluetoothPrinter

  fonts:
    - family: Receipt
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 600
